import { ORG_PERMISSIONS, type OrgPermission } from './org.permissions'

export const ORG_ROLE_PERMISSIONS: Record<
	'admin' | 'organizer' | 'member',
	OrgPermission[]
> = {
  admin: [
    ORG_PERMISSIONS.ORG_VIEW,
    ORG_PERMISSIONS.ORG_UPDATE,
    ORG_PERMISSIONS.ORG_VERIFY_SUBMIT,
    ORG_PERMISSIONS.ORG_MEMBER_INVITE,
    ORG_PERMISSIONS.ORG_MEMBER_REMOVE,

    ORG_PERMISSIONS.EVENT_CREATE,
    ORG_PERMISSIONS.EVENT_EDIT_ANY,
    ORG_PERMISSIONS.EVENT_PUBLISH,
    ORG_PERMISSIONS.EVENT_CANCEL,

    ORG_PERMISSIONS.EVENT_PAID_CREATE,
    ORG_PERMISSIONS.EVENT_REVENUE_VIEW,
  ],

  organizer: [
    ORG_PERMISSIONS.ORG_VIEW,

    ORG_PERMISSIONS.EVENT_CREATE,
    ORG_PERMISSIONS.EVENT_EDIT_OWN,
    ORG_PERMISSIONS.EVENT_PUBLISH,
  ],

  member: [
    ORG_PERMISSIONS.ORG_VIEW,
  ],
}
