import { PERMISSIONS, type Permission } from "./permissions"

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
	admin: [
		PERMISSIONS.EVENTS_ALL,
		PERMISSIONS.EVENTS_FAV,
		PERMISSIONS.EVENTS_TICKET,
		PERMISSIONS.EVENTS_JOIN,
		PERMISSIONS.EVENTS_WISHLIST,

		PERMISSIONS.ACCOUNT_SETTING
	],

	user: [
		PERMISSIONS.EVENTS_ALL,
		PERMISSIONS.EVENTS_FAV,
		PERMISSIONS.EVENTS_TICKET,
		PERMISSIONS.EVENTS_JOIN,
		PERMISSIONS.EVENTS_WISHLIST,

		PERMISSIONS.ACCOUNT_SETTING
	]
}